[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
communication = {path = "../communication"}

flate2 = "1.0"
scrap = "0.5"
enigo = "0.1.3"
rayon = "1.5"
